// dom.js — v0.1.10
const DOM = {
    box: document.getElementById('render-box'),
    canvas: document.getElementById('canvas'),
    text: document.getElementById('ctrl-text'),
    font: document.getElementById('ctrl-font'),
    tracking: document.getElementById('ctrl-tracking'), trackingNum: document.getElementById('ctrl-tracking-num'),
    spacing: document.getElementById('ctrl-spacing'), spacingNum: document.getElementById('ctrl-spacing-num'),
    lineheight: document.getElementById('ctrl-lineheight'), lineheightNum: document.getElementById('ctrl-lineheight-num'),
    bgFit: document.getElementById('ctrl-bg-fit'),
    fontsize: document.getElementById('ctrl-fontsize'), fontsizeNum: document.getElementById('ctrl-fontsize-num'),
    align: document.getElementById('ctrl-align'), alignV: document.getElementById('ctrl-align-v'),
    cText: document.getElementById('ctrl-color-text'), cTextBg: document.getElementById('ctrl-color-text-bg'),
    cStroke: document.getElementById('ctrl-color-stroke'), cBg: document.getElementById('ctrl-color-bg'),
    cTextHex: document.getElementById('ctrl-color-text-hex'), cTextBgHex: document.getElementById('ctrl-color-text-bg-hex'),
    cStrokeHex: document.getElementById('ctrl-color-stroke-hex'), cBgHex: document.getElementById('ctrl-color-bg-hex'),
    pattern: document.getElementById('ctrl-pattern'),
    seedPattern: document.getElementById('ctrl-seed-pattern'), seedPatternNum: document.getElementById('ctrl-seed-pattern-num'),
    seed: document.getElementById('ctrl-seed'), seedNum: document.getElementById('ctrl-seed-num'),
    sWord: document.getElementById('ctrl-stroke-word'), sChar: document.getElementById('ctrl-stroke-char'),
    sWordW: document.getElementById('ctrl-stroke-word-w'), sWordWNum: document.getElementById('ctrl-stroke-word-w-num'),
    sWordRadius: document.getElementById('ctrl-stroke-word-radius'), sWordRadiusNum: document.getElementById('ctrl-stroke-word-radius-num'),
    sWordPadX: document.getElementById('ctrl-stroke-word-padx'), sWordPadXNum: document.getElementById('ctrl-stroke-word-padx-num'),
    sCharW: document.getElementById('ctrl-stroke-char-w'), sCharWNum: document.getElementById('ctrl-stroke-char-w-num'),
    remSpaces: document.getElementById('ctrl-remove-spaces'), wrapText: document.getElementById('ctrl-wrap-text'),
    paletteCont: document.getElementById('palette-container'),
    textReveal: document.getElementById('ctrl-text-reveal'), textRevealNum: document.getElementById('ctrl-text-reveal-num'),
    randomHide: document.getElementById('ctrl-random-hide'), randomHideNum: document.getElementById('ctrl-random-hide-num'),
    revealMode: document.getElementById('ctrl-reveal-mode'),
    randomFont: document.getElementById('ctrl-random-font'),
    fontListCont: document.getElementById('font-list-container'),
    randomFontSection: document.getElementById('random-font-list-section'),
    gradientEnabled: document.getElementById('ctrl-gradient-enabled'),
    gradientSettings: document.getElementById('gradient-settings'),
    gradientType: document.getElementById('ctrl-gradient-type'),
    gradientMode: document.getElementById('ctrl-gradient-mode'),
    gradientAngle: document.getElementById('ctrl-gradient-angle'),
    gradientStrip: document.getElementById('gradient-strip'),
    gradientStopsBar: document.getElementById('gradient-stops-bar'),
    gradientLinearUI: document.getElementById('gradient-linear-ui'),
    gradientRadialUI: document.getElementById('gradient-radial-ui'),
    gradientAngleCanvas: document.getElementById('gradient-angle-canvas'),
    gradientRadialCanvas: document.getElementById('gradient-radial-canvas'),
    gradLx: document.getElementById('ctrl-grad-lx'), gradLxNum: document.getElementById('ctrl-grad-lx-num'),
    gradLy: document.getElementById('ctrl-grad-ly'), gradLyNum: document.getElementById('ctrl-grad-ly-num'),
    gradCx: document.getElementById('ctrl-grad-cx'), gradCxNum: document.getElementById('ctrl-grad-cx-num'),
    gradCy: document.getElementById('ctrl-grad-cy'), gradCyNum: document.getElementById('ctrl-grad-cy-num'),
    gradCr: document.getElementById('ctrl-grad-cr'), gradCrNum: document.getElementById('ctrl-grad-cr-num'),
    frameInput: document.getElementById('timeline-frame'),
    totalFrames: document.getElementById('ctrl-total-frames'),
    fps: document.getElementById('ctrl-fps'),
    zoom: document.getElementById('ctrl-zoom'),
    timelinePanel: document.getElementById('timeline-panel'),
    tlBody: document.getElementById('tl-body'),
    tlSidebar: document.getElementById('tl-sidebar'),
    tlResizer: document.getElementById('timeline-resizer'),
    tracks: document.getElementById('tracks'),
    grid: document.getElementById('timeline-grid'),
    playhead: document.getElementById('playhead'),
    trackables: document.querySelectorAll('.trackable'),
    sidebar: document.getElementById('main-sidebar'),
    playBtn: document.getElementById('btn-play'), playRevBtn: document.getElementById('btn-play-rev'), loopBtn: document.getElementById('btn-loop'),
    prevKfBtn: document.getElementById('btn-prev-kf'), nextKfBtn: document.getElementById('btn-next-kf'),
    goStartBtn: document.getElementById('btn-go-start'), goEndBtn: document.getElementById('btn-go-end'),
    ctxMenu: document.getElementById('context-menu'), ctxTitle: document.getElementById('ctx-title'),
    ctxValue: document.getElementById('ctx-value'), ctxSave: document.getElementById('ctx-save'), ctxDel: document.getElementById('ctx-delete'),
    selBox: document.getElementById('selection-box'),
    exportBtn: document.getElementById('btn-export-json'), importBtn: document.getElementById('btn-import-json'), fileImport: document.getElementById('file-import'),
    btnToggleSidebar: document.getElementById('btn-toggle-sidebar'),
    btnToggleUI: document.getElementById('btn-toggle-ui'),
    fileActionsStack: document.querySelector('.file-actions-stack'),
    resetSpacingBtn: document.getElementById('btn-reset-spacing'),
    fontSearch: document.getElementById('ctrl-font-search'),
    settingsBtn: document.getElementById('btn-settings'), settingsPanel: document.getElementById('settings-panel'),
    btnThemeLight: document.getElementById('btn-theme-light'), btnThemeDark: document.getElementById('btn-theme-dark'),
    btnLangRu: document.getElementById('btn-lang-ru'), btnLangEn: document.getElementById('btn-lang-en'),
    tlEasePresets: document.getElementById('tl-ease-presets'),
    btnEaseLinear: document.getElementById('btn-ease-linear'),
    btnEaseInOut: document.getElementById('btn-ease-inout'),
    btnEaseConst: document.getElementById('btn-ease-const'),
    fullscreenBtn: document.getElementById('btn-fullscreen'),
    exportVideoBtn: document.getElementById('btn-export-video'),
    exportModalOverlay: document.getElementById('export-modal-overlay'),
    expStartFrame: document.getElementById('exp-start-frame'),
    expEndFrame: document.getElementById('exp-end-frame'),
    expFps: document.getElementById('exp-fps'),
    expFormat: document.getElementById('exp-format'),
    expResScreen: document.getElementById('exp-res-screen'),
    expResCustom: document.getElementById('exp-res-custom'),
    expResCustomRow: document.getElementById('exp-res-custom-row'),
    expResInfo: document.getElementById('exp-res-info'),
    expWidth: document.getElementById('exp-width'),
    expHeight: document.getElementById('exp-height'),
    expBtnStart: document.getElementById('exp-btn-start'),
    expBtnCancelModal: document.getElementById('exp-btn-cancel-modal'),
    expSettingsSection: document.getElementById('export-settings-section'),
};